create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null default '',
  role text not null default 'student' check (role in ('student','admin')),
  status text not null default 'pending' check (status in ('pending','active','blocked')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id,name,email,role,status)
  values (new.id,coalesce(new.raw_user_meta_data ->> 'name',''),coalesce(new.email,''),'student','pending');
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and status = 'active'
  );
$$;

drop policy if exists "user read own" on public.profiles;
create policy "user read own" on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "admin read all" on public.profiles;
create policy "admin read all" on public.profiles for select to authenticated using (public.is_admin());

drop policy if exists "admin update all" on public.profiles;
create policy "admin update all" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.weeks (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs(id) on delete cascade,
  week_number int not null,
  title text
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  week_id bigint not null references public.weeks(id) on delete cascade,
  lesson_number int not null,
  title text not null,
  description text
);

create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  title text not null,
  video_url text,
  sets text,
  repetitions text,
  rest_seconds int,
  sort_order int not null default 0
);

create table if not exists public.student_programs (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete cascade,
  starts_at date not null default current_date,
  ends_at date,
  active boolean not null default true,
  unique(student_id, program_id)
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  unique(student_id, lesson_id)
);

-- Depois de criar sua própria conta, torne-a admin com:
-- update public.profiles set role='admin', status='active' where id='SEU-UUID';
