-- P3 lote 2 — notificações administrativas em tempo real
-- JÁ APLICADA no Supabase de produção em 2026-09-03.
-- Este arquivo existe para manter o histórico do repositório sincronizado.

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('new_student', 'program_completed')),
  title text not null,
  message text not null,
  student_id uuid null references public.profiles(id) on delete cascade,
  program_id bigint null references public.programs(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text not null unique,
  created_at timestamptz not null default now(),
  read_at timestamptz null
);

create index if not exists admin_notifications_student_id_idx
  on public.admin_notifications (student_id);
create index if not exists admin_notifications_program_id_idx
  on public.admin_notifications (program_id);
create index if not exists admin_notifications_created_at_idx
  on public.admin_notifications (created_at desc);
create index if not exists admin_notifications_unread_idx
  on public.admin_notifications (created_at desc)
  where read_at is null;

alter table public.admin_notifications enable row level security;

drop policy if exists "admin notifications select" on public.admin_notifications;
drop policy if exists "admin notifications update" on public.admin_notifications;

create policy "admin notifications select"
on public.admin_notifications
for select
to authenticated
using ((select private.is_admin()));

create policy "admin notifications update"
on public.admin_notifications
for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

grant select, update on public.admin_notifications to authenticated;
revoke insert, delete on public.admin_notifications from anon, authenticated;

create or replace function private.notify_new_student_registration()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.role = 'student' and new.status = 'pending' then
    insert into public.admin_notifications (
      kind, title, message, student_id, metadata, dedupe_key, created_at
    )
    values (
      'new_student',
      'Novo aluno aguardando aprovação',
      coalesce(nullif(new.name, ''), 'Novo aluno') ||
        ' realizou o cadastro e aguarda liberação.',
      new.id,
      jsonb_build_object('name', new.name, 'email', new.email),
      'student_registered:' || new.id::text,
      new.created_at
    )
    on conflict (dedupe_key) do nothing;
  end if;
  return new;
end;
$$;

revoke all on function private.notify_new_student_registration()
from public, anon, authenticated;

drop trigger if exists on_profile_created_admin_notification
on public.profiles;

create trigger on_profile_created_admin_notification
after insert on public.profiles
for each row
execute function private.notify_new_student_registration();

create or replace function private.notify_program_completion()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_program_id bigint;
  v_program_title text;
  v_student_name text;
  v_total_lessons integer;
  v_completed_lessons integer;
begin
  if new.completed is not true then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.completed is true then
    return new;
  end if;

  select sp.program_id, p.title
    into v_program_id, v_program_title
  from public.student_programs sp
  join public.programs p on p.id = sp.program_id
  join public.weeks w on w.program_id = sp.program_id
  join public.lessons l on l.week_id = w.id
  where sp.student_id = new.student_id
    and sp.active = true
    and l.id = new.lesson_id
  limit 1;

  if v_program_id is null then
    return new;
  end if;

  select count(*)::integer
    into v_total_lessons
  from public.lessons l
  join public.weeks w on w.id = l.week_id
  where w.program_id = v_program_id;

  if v_total_lessons <= 0 then
    return new;
  end if;

  select count(*)::integer
    into v_completed_lessons
  from public.lesson_progress lp
  join public.lessons l on l.id = lp.lesson_id
  join public.weeks w on w.id = l.week_id
  where lp.student_id = new.student_id
    and lp.completed = true
    and w.program_id = v_program_id;

  if v_completed_lessons < v_total_lessons then
    return new;
  end if;

  select name into v_student_name
  from public.profiles
  where id = new.student_id;

  insert into public.admin_notifications (
    kind, title, message, student_id, program_id, metadata, dedupe_key
  )
  values (
    'program_completed',
    'Metodologia concluída',
    coalesce(nullif(v_student_name, ''), 'Aluno') ||
      ' concluiu 100% de ' ||
      coalesce(v_program_title, 'sua metodologia') || '.',
    new.student_id,
    v_program_id,
    jsonb_build_object(
      'student_name', v_student_name,
      'program_title', v_program_title,
      'completed_lessons', v_completed_lessons,
      'total_lessons', v_total_lessons
    ),
    'program_completed:' || new.student_id::text || ':' || v_program_id::text
  )
  on conflict (dedupe_key) do nothing;

  return new;
end;
$$;

revoke all on function private.notify_program_completion()
from public, anon, authenticated;

drop trigger if exists on_lesson_progress_admin_notification
on public.lesson_progress;

create trigger on_lesson_progress_admin_notification
after insert or update of completed on public.lesson_progress
for each row
execute function private.notify_program_completion();

insert into public.admin_notifications (
  kind, title, message, student_id, metadata, dedupe_key, created_at
)
select
  'new_student',
  'Novo aluno aguardando aprovação',
  coalesce(nullif(p.name, ''), 'Novo aluno') ||
    ' realizou o cadastro e aguarda liberação.',
  p.id,
  jsonb_build_object('name', p.name, 'email', p.email),
  'student_registered:' || p.id::text,
  p.created_at
from public.profiles p
where p.role = 'student'
  and p.status = 'pending'
on conflict (dedupe_key) do nothing;

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'admin_notifications'
  ) then
    alter publication supabase_realtime
      add table public.admin_notifications;
  end if;
end;
$$;
