-- P3 lote 3 — infraestrutura de Web Push administrativo
-- JÁ APLICADA no Supabase de produção em 2026-09-03.
-- NÃO contém chaves privadas nem segredo de webhook.
-- Esses valores foram provisionados diretamente no ambiente de produção
-- e não devem ser versionados.

create extension if not exists pg_net;

create table if not exists public.admin_push_subscriptions (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_push_subscriptions_admin_id_idx
  on public.admin_push_subscriptions (admin_id);

create index if not exists admin_push_subscriptions_active_idx
  on public.admin_push_subscriptions (active)
  where active = true;

alter table public.admin_push_subscriptions enable row level security;

drop policy if exists "admin push subscriptions select own"
  on public.admin_push_subscriptions;
drop policy if exists "admin push subscriptions insert own"
  on public.admin_push_subscriptions;
drop policy if exists "admin push subscriptions update own"
  on public.admin_push_subscriptions;
drop policy if exists "admin push subscriptions delete own"
  on public.admin_push_subscriptions;

create policy "admin push subscriptions select own"
on public.admin_push_subscriptions
for select
to authenticated
using (
  (select private.is_admin())
  and admin_id = (select auth.uid())
);

create policy "admin push subscriptions insert own"
on public.admin_push_subscriptions
for insert
to authenticated
with check (
  (select private.is_admin())
  and admin_id = (select auth.uid())
);

create policy "admin push subscriptions update own"
on public.admin_push_subscriptions
for update
to authenticated
using (
  (select private.is_admin())
  and admin_id = (select auth.uid())
)
with check (
  (select private.is_admin())
  and admin_id = (select auth.uid())
);

create policy "admin push subscriptions delete own"
on public.admin_push_subscriptions
for delete
to authenticated
using (
  (select private.is_admin())
  and admin_id = (select auth.uid())
);

grant select, insert, update, delete
  on public.admin_push_subscriptions
  to authenticated;

grant usage, select
  on sequence public.admin_push_subscriptions_id_seq
  to authenticated;

create table if not exists private.admin_push_config (
  singleton boolean primary key default true check (singleton),
  vapid_subject text not null,
  vapid_public_key text not null,
  vapid_private_key text not null,
  webhook_secret text not null,
  edge_function_url text not null,
  updated_at timestamptz not null default now()
);

revoke all on private.admin_push_config
from public, anon, authenticated;

create or replace function public.get_admin_push_delivery_config()
returns table (
  vapid_subject text,
  vapid_public_key text,
  vapid_private_key text,
  webhook_secret text
)
language sql
security definer
set search_path = ''
as $$
  select
    c.vapid_subject,
    c.vapid_public_key,
    c.vapid_private_key,
    c.webhook_secret
  from private.admin_push_config c
  where c.singleton = true
  limit 1;
$$;

revoke all
on function public.get_admin_push_delivery_config()
from public, anon, authenticated;

grant execute
on function public.get_admin_push_delivery_config()
to service_role;

create or replace function private.dispatch_admin_web_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_url text;
  v_secret text;
begin
  select edge_function_url, webhook_secret
    into v_url, v_secret
  from private.admin_push_config
  where singleton = true;

  if v_url is null or v_secret is null then
    return new;
  end if;

  perform net.http_post(
    url := v_url,
    body := jsonb_build_object('notification_id', new.id),
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-rv-push-secret', v_secret
    ),
    timeout_milliseconds := 4000
  );

  return new;
exception
  when others then
    raise warning 'RV push dispatch failed: %', sqlerrm;
    return new;
end;
$$;

revoke all
on function private.dispatch_admin_web_push()
from public, anon, authenticated;

drop trigger if exists on_admin_notification_web_push
on public.admin_notifications;

create trigger on_admin_notification_web_push
after insert on public.admin_notifications
for each row
execute function private.dispatch_admin_web_push();

-- IMPORTANTE:
-- private.admin_push_config fica propositalmente sem INSERT neste arquivo.
-- Produção já foi provisionada sem expor VAPID_PRIVATE_KEY/webhook_secret.
